rds_db_name                   = "aws-free-infra_db"
rds_username                  = "root"
rds_password                  = "password"
s3_user_aws_access_key_id     = "s3_user_aws_access_key_id"
s3_user_aws_secret_access_key = "s3_user_aws_secret_access_key"
token_key                     = "token_key"
